#!/usr/bin/env bash
#
# Evaluates a file with bash variable substitution.
#
# Usage: shab [template-file|-]
set -euo pipefail

# eponymously slow cat ersatz hostile to nulls
dog() {
    [[ "${1-}" != - ]] || set --
    eval '
    while IFS= read -r line; do
        printf "%s\n" "$line"
    done '${1+<"$1"}'
    printf "%s" "$line"
    '
}

if ! type -P cat &>/dev/null; then
  alias cat=dog
fi

shab() {(
  local id=${RANDOM}_${RANDOM}
  eval "$(echo "set -eu; cat <<SHAB_$id"; cat "${1:--}"; echo; echo "SHAB_$id")"
)}

# Works both as a sourced file or executable
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  shab "$@"
fi
