#!/usr/bin/env bash
#
# Evaluates a file with bash variable substitution.
#
# Usage: shab <template-file>
set -euo pipefail

shab() {(
    local id=${RANDOM}_${RANDOM}
    local tmp=${TMPDIR:-/tmp}/shab.$id
    trap 'rm -f $tmp' EXIT
    set -o noclobber

    (
        echo "set -eu; cat <<TEMPLATE_CONTENT_$id"
        cat "$1"
        echo
        echo "TEMPLATE_CONTENT_$id"
    ) > "$tmp"

    source "$tmp"
)}

# Works both as a sourced file or executable
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  shab "$@"
fi
